name: Build ESP32-S3 Firmware

on:
  workflow_dispatch:
  release:
    types: [published]
          
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install Arduino-cli
      run: |
        wget -O arduino-cli.deb https://github.com/arduino/arduino-cli/releases/download/v1.5.1/arduino-cli_1.5.1-1_amd64.deb
        sudo dpkg -i arduino-cli.deb
        sudo apt --fix-broken install -y
        sudo dpkg --configure -a
        
        arduino-cli config init
        arduino-cli config add board_manager.additional_urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
        arduino-cli core update-index
        arduino-cli core install esp32:esp32        

        # Install libraries
        # DHT22 Library Install
        arduino-cli lib install "Adafruit Unified Sensor"
        git clone https://github.com/adafruit/DHT-sensor-library.git ~/Arduino/libraries/DHT-sensor-library
        
        # Compile Firmware
        cd ESP32S3
        mv *.ino ESP32S3.ino
        arduino-cli compile --fqbn esp32:esp32:esp32s3:FlashSize=16M,PSRAM=opi --clean --output-dir firmware .

        # Rename File   
        rm firmware/*.ino.bin             
        rm firmware/*.ino.bootloader.bin  
        rm firmware/*.ino.partitions.bin
        
        mv firmware/*.ino.merged.bin      firmware/esp32s3-dht22-firmware-0x0.bin
         
    - name: Determine release tag
      id: get_tag
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          TAG_NAME="${{ github.event.release.tag_name }}"
        else
          TAG_NAME="esp32s3"
        fi
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

    - name: Upload files to existing release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ steps.get_tag.outputs.tag_name }}
        files: |
          ESP32S3/firmware/*.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
